# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(214, 370, 301, 131))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 70, 221, 141))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 190, 161, 101))
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 160, 81, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 190, 81, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu_Stuff = QtWidgets.QMenu(self.menubar)
        self.menuMenu_Stuff.setObjectName("menuMenu_Stuff")
        self.menuOther_Stuff = QtWidgets.QMenu(self.menubar)
        self.menuOther_Stuff.setObjectName("menuOther_Stuff")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionA_button = QtWidgets.QAction(MainWindow)
        self.actionA_button.setObjectName("actionA_button")
        self.actionAnother_button = QtWidgets.QAction(MainWindow)
        self.actionAnother_button.setObjectName("actionAnother_button")
        self.actionYet_another_button = QtWidgets.QAction(MainWindow)
        self.actionYet_another_button.setObjectName("actionYet_another_button")
        self.menuMenu_Stuff.addAction(self.actionA_button)
        self.menuMenu_Stuff.addAction(self.actionAnother_button)
        self.menuOther_Stuff.addAction(self.actionYet_another_button)
        self.menubar.addAction(self.menuMenu_Stuff.menuAction())
        self.menubar.addAction(self.menuOther_Stuff.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "None-Functional Button"))
        self.label.setText(_translate("MainWindow", "This is a label"))
        self.label_2.setText(_translate("MainWindow", "This is another label"))
        self.checkBox.setText(_translate("MainWindow", "Check 1"))
        self.checkBox_2.setText(_translate("MainWindow", "Check 2"))
        self.menuMenu_Stuff.setTitle(_translate("MainWindow", "Menu Stuff"))
        self.menuOther_Stuff.setTitle(_translate("MainWindow", "Other Stuff"))
        self.actionA_button.setText(_translate("MainWindow", "A button"))
        self.actionAnother_button.setText(_translate("MainWindow", "Another button"))
        self.actionYet_another_button.setText(_translate("MainWindow", "Yet another button"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
