# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pressMe = QtWidgets.QPushButton(self.centralwidget)
        self.pressMe.setGeometry(QtCore.QRect(240, 450, 261, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pressMe.setFont(font)
        self.pressMe.setObjectName("pressMe")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(270, 280, 133, 20))
        self.lineEdit1.setObjectName("lineEdit1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 21))
        self.menubar.setObjectName("menubar")
        self.menuAdd_File = QtWidgets.QMenu(self.menubar)
        self.menuAdd_File.setObjectName("menuAdd_File")
        self.menuFeatures = QtWidgets.QMenu(self.menubar)
        self.menuFeatures.setObjectName("menuFeatures")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.menuAdd_File.addAction(self.actionSave)
        self.menuAdd_File.addAction(self.actionSave_as)
        self.menuAdd_File.addAction(self.actionLoad)
        self.menuAdd_File.addAction(self.actionNew_project)
        self.menubar.addAction(self.menuAdd_File.menuAction())
        self.menubar.addAction(self.menuFeatures.menuAction())

        self.retranslateUi(MainWindow)
        self.pressMe.clicked.connect(self.lineEdit1.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pressMe.setText(_translate("MainWindow", "Press Me!"))
        self.menuAdd_File.setTitle(_translate("MainWindow", "Menu"))
        self.menuFeatures.setTitle(_translate("MainWindow", "Features"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "THIS IS A TIP"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionNew_project.setText(_translate("MainWindow", "New project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
