# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_top.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.frame_top)
        self.frame_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toggle)
        self.btn_toggle.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_toggle.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 85);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.btn_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggle.setIcon(icon)
        self.btn_toggle.setIconSize(QtCore.QSize(24, 24))
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_13.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_descriptions = QtWidgets.QFrame(self.frame_top)
        self.frame_descriptions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_descriptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_descriptions.setObjectName("frame_descriptions")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_descriptions)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_descriptions)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_title.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_7.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_7.addWidget(self.label_title)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.frame_file_location = QtWidgets.QFrame(self.frame_descriptions)
        self.frame_file_location.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"\n"
"border-top: 1px solid  rgba(224, 224, 224, 0.2);")
        self.frame_file_location.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_file_location.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file_location.setObjectName("frame_file_location")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_file_location)
        self.horizontalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_file_location = QtWidgets.QLabel(self.frame_file_location)
        self.label_file_location.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-top: none;")
        self.label_file_location.setObjectName("label_file_location")
        self.horizontalLayout_8.addWidget(self.label_file_location)
        self.verticalLayout_2.addWidget(self.frame_file_location)
        self.horizontalLayout.addWidget(self.frame_descriptions)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        self.frame_content.setStyleSheet("")
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_menu = QtWidgets.QFrame(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu.sizePolicy().hasHeightForWidth())
        self.frame_menu.setSizePolicy(sizePolicy)
        self.frame_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame_menu.setStyleSheet("background-color: rgb(56, 55, 57);")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menu = QtWidgets.QFrame(self.frame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_menu.sizePolicy().hasHeightForWidth())
        self.frame_top_menu.setSizePolicy(sizePolicy)
        self.frame_top_menu.setStyleSheet("")
        self.frame_top_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menu.setObjectName("frame_top_menu")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_top_menu)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_menu_3 = QtWidgets.QFrame(self.frame_top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu_3.sizePolicy().hasHeightForWidth())
        self.frame_menu_3.setSizePolicy(sizePolicy)
        self.frame_menu_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_menu_3.setStyleSheet("QFrame, QPushButton{\n"
"    background-color: rgb(56, 55, 57);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.frame_menu_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_3.setObjectName("frame_menu_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_menu_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_btn_design = QtWidgets.QFrame(self.frame_menu_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btn_design.sizePolicy().hasHeightForWidth())
        self.frame_btn_design.setSizePolicy(sizePolicy)
        self.frame_btn_design.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_btn_design.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_btn_design.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btn_design.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_design.setObjectName("frame_btn_design")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_btn_design)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_design = QtWidgets.QPushButton(self.frame_btn_design)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_design.sizePolicy().hasHeightForWidth())
        self.btn_design.setSizePolicy(sizePolicy)
        self.btn_design.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_design.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_design.setStyleSheet("")
        self.btn_design.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/prototype.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_design.setIcon(icon1)
        self.btn_design.setIconSize(QtCore.QSize(30, 30))
        self.btn_design.setObjectName("btn_design")
        self.verticalLayout_8.addWidget(self.btn_design)
        self.horizontalLayout_5.addWidget(self.frame_btn_design)
        self.frame_label_design = QtWidgets.QFrame(self.frame_menu_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_design.sizePolicy().hasHeightForWidth())
        self.frame_label_design.setSizePolicy(sizePolicy)
        self.frame_label_design.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_label_design.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_label_design.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_design.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_design.setObjectName("frame_label_design")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_label_design)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_design = QtWidgets.QLabel(self.frame_label_design)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_design.sizePolicy().hasHeightForWidth())
        self.label_design.setSizePolicy(sizePolicy)
        self.label_design.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_design.setFont(font)
        self.label_design.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_design.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_design.setWordWrap(True)
        self.label_design.setObjectName("label_design")
        self.verticalLayout_9.addWidget(self.label_design)
        self.horizontalLayout_5.addWidget(self.frame_label_design)
        self.verticalLayout_10.addWidget(self.frame_menu_3)
        self.frame_menu_2 = QtWidgets.QFrame(self.frame_top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu_2.sizePolicy().hasHeightForWidth())
        self.frame_menu_2.setSizePolicy(sizePolicy)
        self.frame_menu_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_menu_2.setStyleSheet("QFrame, QPushButton{\n"
"    background-color: rgb(56, 55, 57);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.frame_menu_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_2.setObjectName("frame_menu_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_menu_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_btn_convert = QtWidgets.QFrame(self.frame_menu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btn_convert.sizePolicy().hasHeightForWidth())
        self.frame_btn_convert.setSizePolicy(sizePolicy)
        self.frame_btn_convert.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_btn_convert.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_btn_convert.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btn_convert.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_convert.setObjectName("frame_btn_convert")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_btn_convert)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_convert = QtWidgets.QPushButton(self.frame_btn_convert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_convert.sizePolicy().hasHeightForWidth())
        self.btn_convert.setSizePolicy(sizePolicy)
        self.btn_convert.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_convert.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_convert.setStyleSheet("")
        self.btn_convert.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/circuit-board.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_convert.setIcon(icon2)
        self.btn_convert.setIconSize(QtCore.QSize(30, 30))
        self.btn_convert.setObjectName("btn_convert")
        self.verticalLayout_6.addWidget(self.btn_convert)
        self.horizontalLayout_4.addWidget(self.frame_btn_convert)
        self.frame_label_convert = QtWidgets.QFrame(self.frame_menu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_convert.sizePolicy().hasHeightForWidth())
        self.frame_label_convert.setSizePolicy(sizePolicy)
        self.frame_label_convert.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_label_convert.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_label_convert.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_convert.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_convert.setObjectName("frame_label_convert")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_label_convert)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_convert = QtWidgets.QLabel(self.frame_label_convert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_convert.sizePolicy().hasHeightForWidth())
        self.label_convert.setSizePolicy(sizePolicy)
        self.label_convert.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_convert.setFont(font)
        self.label_convert.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_convert.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_convert.setWordWrap(True)
        self.label_convert.setObjectName("label_convert")
        self.verticalLayout_7.addWidget(self.label_convert)
        self.horizontalLayout_4.addWidget(self.frame_label_convert)
        self.verticalLayout_10.addWidget(self.frame_menu_2)
        self.frame_menu_1 = QtWidgets.QFrame(self.frame_top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu_1.sizePolicy().hasHeightForWidth())
        self.frame_menu_1.setSizePolicy(sizePolicy)
        self.frame_menu_1.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_menu_1.setStyleSheet("QFrame, QPushButton{\n"
"    background-color: rgb(56, 55, 57);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.frame_menu_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_1.setObjectName("frame_menu_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_menu_1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_btn_file = QtWidgets.QFrame(self.frame_menu_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btn_file.sizePolicy().hasHeightForWidth())
        self.frame_btn_file.setSizePolicy(sizePolicy)
        self.frame_btn_file.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_btn_file.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_btn_file.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btn_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_file.setObjectName("frame_btn_file")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_btn_file)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_file = QtWidgets.QPushButton(self.frame_btn_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_file.sizePolicy().hasHeightForWidth())
        self.btn_file.setSizePolicy(sizePolicy)
        self.btn_file.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_file.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_file.setStyleSheet("")
        self.btn_file.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file.setIcon(icon3)
        self.btn_file.setIconSize(QtCore.QSize(24, 24))
        self.btn_file.setObjectName("btn_file")
        self.verticalLayout_4.addWidget(self.btn_file)
        self.horizontalLayout_3.addWidget(self.frame_btn_file)
        self.frame_label_file = QtWidgets.QFrame(self.frame_menu_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_file.sizePolicy().hasHeightForWidth())
        self.frame_label_file.setSizePolicy(sizePolicy)
        self.frame_label_file.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_label_file.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_label_file.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_file.setObjectName("frame_label_file")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_label_file)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_file = QtWidgets.QLabel(self.frame_label_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_file.sizePolicy().hasHeightForWidth())
        self.label_file.setSizePolicy(sizePolicy)
        self.label_file.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_file.setFont(font)
        self.label_file.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_file.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_file.setWordWrap(True)
        self.label_file.setObjectName("label_file")
        self.verticalLayout_5.addWidget(self.label_file)
        self.horizontalLayout_3.addWidget(self.frame_label_file)
        self.verticalLayout_10.addWidget(self.frame_menu_1)
        self.verticalLayout_3.addWidget(self.frame_top_menu, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_menu)
        self.frame_workspaces = QtWidgets.QFrame(self.frame_content)
        self.frame_workspaces.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_workspaces.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_workspaces.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_workspaces.setObjectName("frame_workspaces")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_workspaces)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.stacked_workspaces = QtWidgets.QStackedWidget(self.frame_workspaces)
        self.stacked_workspaces.setMinimumSize(QtCore.QSize(0, 0))
        self.stacked_workspaces.setStyleSheet("background-color: rgb(224, 224, 224);")
        self.stacked_workspaces.setObjectName("stacked_workspaces")
        self.page_design = QtWidgets.QWidget()
        self.page_design.setObjectName("page_design")
        self.label_page_design = QtWidgets.QLabel(self.page_design)
        self.label_page_design.setGeometry(QtCore.QRect(430, 160, 301, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_page_design.setFont(font)
        self.label_page_design.setObjectName("label_page_design")
        self.stacked_workspaces.addWidget(self.page_design)
        self.page_convert = QtWidgets.QWidget()
        self.page_convert.setObjectName("page_convert")
        self.label_page_convert = QtWidgets.QLabel(self.page_convert)
        self.label_page_convert.setGeometry(QtCore.QRect(320, 260, 391, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_page_convert.setFont(font)
        self.label_page_convert.setObjectName("label_page_convert")
        self.stacked_workspaces.addWidget(self.page_convert)
        self.page_file = QtWidgets.QWidget()
        self.page_file.setObjectName("page_file")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_file)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_7 = QtWidgets.QFrame(self.page_file)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_23.addWidget(self.label_4)
        self.verticalLayout_15.addWidget(self.frame_7)
        self.btn_file_menu = QtWidgets.QFrame(self.page_file)
        self.btn_file_menu.setMinimumSize(QtCore.QSize(0, 500))
        self.btn_file_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btn_file_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_file_menu.setObjectName("btn_file_menu")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.btn_file_menu)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.btn_top_file_menu = QtWidgets.QFrame(self.btn_file_menu)
        self.btn_top_file_menu.setMinimumSize(QtCore.QSize(0, 200))
        self.btn_top_file_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btn_top_file_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_top_file_menu.setObjectName("btn_top_file_menu")
        self.gridLayout = QtWidgets.QGridLayout(self.btn_top_file_menu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.btn_top_file_menu)
        self.frame.setMaximumSize(QtCore.QSize(586, 16777215))
        self.frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_17.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 85);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_17.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.label_create_new = QtWidgets.QFrame(self.btn_top_file_menu)
        self.label_create_new.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_create_new.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_create_new.setObjectName("label_create_new")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.label_create_new)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label = QtWidgets.QLabel(self.label_create_new)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_20.addWidget(self.label)
        self.gridLayout.addWidget(self.label_create_new, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.btn_top_file_menu)
        self.frame_3.setMaximumSize(QtCore.QSize(586, 16777215))
        self.frame_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_18.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 85);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.pushButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/open-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_18.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.btn_top_file_menu)
        self.frame_5.setMaximumSize(QtCore.QSize(586, 16777215))
        self.frame_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_19.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 85);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.pushButton_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_19.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.frame_5, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.btn_top_file_menu)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_22.addWidget(self.label_3)
        self.gridLayout.addWidget(self.frame_6, 2, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.btn_top_file_menu)
        self.frame_9.setMaximumSize(QtCore.QSize(586, 16777215))
        self.frame_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_25.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 85);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(42, 41, 44);\n"
"}")
        self.pushButton_4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/Save As.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_25.addWidget(self.pushButton_4)
        self.gridLayout.addWidget(self.frame_9, 3, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.btn_top_file_menu)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_24.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_8, 3, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.btn_top_file_menu)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_21.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.btn_top_file_menu, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_15.addWidget(self.btn_file_menu)
        self.stacked_workspaces.addWidget(self.page_file)
        self.verticalLayout_14.addWidget(self.stacked_workspaces)
        self.horizontalLayout_2.addWidget(self.frame_workspaces)
        self.frame_tools = QtWidgets.QFrame(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_tools.sizePolicy().hasHeightForWidth())
        self.frame_tools.setSizePolicy(sizePolicy)
        self.frame_tools.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_tools.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_tools.setStyleSheet("background-color: rgb(42, 41, 44);")
        self.frame_tools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tools.setObjectName("frame_tools")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_tools)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_top_extra_tools = QtWidgets.QFrame(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_extra_tools.sizePolicy().hasHeightForWidth())
        self.frame_top_extra_tools.setSizePolicy(sizePolicy)
        self.frame_top_extra_tools.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_top_extra_tools.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"")
        self.frame_top_extra_tools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_extra_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_extra_tools.setObjectName("frame_top_extra_tools")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_top_extra_tools)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.stacked_tools = QtWidgets.QStackedWidget(self.frame_top_extra_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_tools.sizePolicy().hasHeightForWidth())
        self.stacked_tools.setSizePolicy(sizePolicy)
        self.stacked_tools.setObjectName("stacked_tools")
        self.page_components = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_components.sizePolicy().hasHeightForWidth())
        self.page_components.setSizePolicy(sizePolicy)
        self.page_components.setObjectName("page_components")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_components)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_resistor = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_resistor.sizePolicy().hasHeightForWidth())
        self.btn_resistor.setSizePolicy(sizePolicy)
        self.btn_resistor.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_resistor.setObjectName("btn_resistor")
        self.verticalLayout_11.addWidget(self.btn_resistor)
        self.btn_capacitor = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_capacitor.sizePolicy().hasHeightForWidth())
        self.btn_capacitor.setSizePolicy(sizePolicy)
        self.btn_capacitor.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_capacitor.setObjectName("btn_capacitor")
        self.verticalLayout_11.addWidget(self.btn_capacitor)
        self.btn_diode = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_diode.sizePolicy().hasHeightForWidth())
        self.btn_diode.setSizePolicy(sizePolicy)
        self.btn_diode.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_diode.setObjectName("btn_diode")
        self.verticalLayout_11.addWidget(self.btn_diode)
        self.btn_led = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_led.sizePolicy().hasHeightForWidth())
        self.btn_led.setSizePolicy(sizePolicy)
        self.btn_led.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_led.setObjectName("btn_led")
        self.verticalLayout_11.addWidget(self.btn_led)
        self.btn_inductor = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_inductor.sizePolicy().hasHeightForWidth())
        self.btn_inductor.setSizePolicy(sizePolicy)
        self.btn_inductor.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_inductor.setObjectName("btn_inductor")
        self.verticalLayout_11.addWidget(self.btn_inductor)
        self.btn_npn_transistor = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_npn_transistor.sizePolicy().hasHeightForWidth())
        self.btn_npn_transistor.setSizePolicy(sizePolicy)
        self.btn_npn_transistor.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_npn_transistor.setObjectName("btn_npn_transistor")
        self.verticalLayout_11.addWidget(self.btn_npn_transistor)
        self.btn_pnp_transistor = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pnp_transistor.sizePolicy().hasHeightForWidth())
        self.btn_pnp_transistor.setSizePolicy(sizePolicy)
        self.btn_pnp_transistor.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_pnp_transistor.setObjectName("btn_pnp_transistor")
        self.verticalLayout_11.addWidget(self.btn_pnp_transistor)
        self.btn_switch = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_switch.sizePolicy().hasHeightForWidth())
        self.btn_switch.setSizePolicy(sizePolicy)
        self.btn_switch.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_switch.setObjectName("btn_switch")
        self.verticalLayout_11.addWidget(self.btn_switch)
        self.btn_ground = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ground.sizePolicy().hasHeightForWidth())
        self.btn_ground.setSizePolicy(sizePolicy)
        self.btn_ground.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_ground.setObjectName("btn_ground")
        self.verticalLayout_11.addWidget(self.btn_ground)
        self.btn_voltage = QtWidgets.QPushButton(self.page_components)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_voltage.sizePolicy().hasHeightForWidth())
        self.btn_voltage.setSizePolicy(sizePolicy)
        self.btn_voltage.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_voltage.setStyleSheet("border: none;")
        self.btn_voltage.setObjectName("btn_voltage")
        self.verticalLayout_11.addWidget(self.btn_voltage)
        self.stacked_tools.addWidget(self.page_components)
        self.page_colors = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_colors.sizePolicy().hasHeightForWidth())
        self.page_colors.setSizePolicy(sizePolicy)
        self.page_colors.setObjectName("page_colors")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page_colors)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.btn_black = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_black.sizePolicy().hasHeightForWidth())
        self.btn_black.setSizePolicy(sizePolicy)
        self.btn_black.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_black.setObjectName("btn_black")
        self.verticalLayout_26.addWidget(self.btn_black)
        self.btn_red = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_red.sizePolicy().hasHeightForWidth())
        self.btn_red.setSizePolicy(sizePolicy)
        self.btn_red.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_red.setObjectName("btn_red")
        self.verticalLayout_26.addWidget(self.btn_red)
        self.btn_orange = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_orange.sizePolicy().hasHeightForWidth())
        self.btn_orange.setSizePolicy(sizePolicy)
        self.btn_orange.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_orange.setObjectName("btn_orange")
        self.verticalLayout_26.addWidget(self.btn_orange)
        self.btn_yellow = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_yellow.sizePolicy().hasHeightForWidth())
        self.btn_yellow.setSizePolicy(sizePolicy)
        self.btn_yellow.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_yellow.setObjectName("btn_yellow")
        self.verticalLayout_26.addWidget(self.btn_yellow)
        self.btn_green = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_green.sizePolicy().hasHeightForWidth())
        self.btn_green.setSizePolicy(sizePolicy)
        self.btn_green.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_green.setObjectName("btn_green")
        self.verticalLayout_26.addWidget(self.btn_green)
        self.btn_blue = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_blue.sizePolicy().hasHeightForWidth())
        self.btn_blue.setSizePolicy(sizePolicy)
        self.btn_blue.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_blue.setObjectName("btn_blue")
        self.verticalLayout_26.addWidget(self.btn_blue)
        self.btn_purple = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_purple.sizePolicy().hasHeightForWidth())
        self.btn_purple.setSizePolicy(sizePolicy)
        self.btn_purple.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_purple.setObjectName("btn_purple")
        self.verticalLayout_26.addWidget(self.btn_purple)
        self.btn_pink = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pink.sizePolicy().hasHeightForWidth())
        self.btn_pink.setSizePolicy(sizePolicy)
        self.btn_pink.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_pink.setObjectName("btn_pink")
        self.verticalLayout_26.addWidget(self.btn_pink)
        self.btn_cyan = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cyan.sizePolicy().hasHeightForWidth())
        self.btn_cyan.setSizePolicy(sizePolicy)
        self.btn_cyan.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_cyan.setObjectName("btn_cyan")
        self.verticalLayout_26.addWidget(self.btn_cyan)
        self.btn_brown = QtWidgets.QPushButton(self.page_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_brown.sizePolicy().hasHeightForWidth())
        self.btn_brown.setSizePolicy(sizePolicy)
        self.btn_brown.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_brown.setObjectName("btn_brown")
        self.verticalLayout_26.addWidget(self.btn_brown)
        self.stacked_tools.addWidget(self.page_colors)
        self.verticalLayout_27.addWidget(self.stacked_tools, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_6.addWidget(self.frame_top_extra_tools)
        self.frame_top_tools = QtWidgets.QFrame(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_tools.sizePolicy().hasHeightForWidth())
        self.frame_top_tools.setSizePolicy(sizePolicy)
        self.frame_top_tools.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_top_tools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_tools.setObjectName("frame_top_tools")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_top_tools)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_wire = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_wire.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_wire.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"\n"
"")
        self.btn_wire.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/wires.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wire.setIcon(icon8)
        self.btn_wire.setIconSize(QtCore.QSize(24, 24))
        self.btn_wire.setCheckable(False)
        self.btn_wire.setChecked(False)
        self.btn_wire.setObjectName("btn_wire")
        self.verticalLayout_12.addWidget(self.btn_wire)
        self.btn_snip = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_snip.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_snip.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"")
        self.btn_snip.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_snip.setIcon(icon9)
        self.btn_snip.setIconSize(QtCore.QSize(24, 24))
        self.btn_snip.setCheckable(False)
        self.btn_snip.setChecked(False)
        self.btn_snip.setObjectName("btn_snip")
        self.verticalLayout_12.addWidget(self.btn_snip)
        self.btn_add = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_add.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_add.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"")
        self.btn_add.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/circuit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon10)
        self.btn_add.setIconSize(QtCore.QSize(24, 24))
        self.btn_add.setCheckable(False)
        self.btn_add.setChecked(False)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout_12.addWidget(self.btn_add)
        self.btn_delete = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_delete.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_delete.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"")
        self.btn_delete.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon11)
        self.btn_delete.setIconSize(QtCore.QSize(24, 24))
        self.btn_delete.setCheckable(False)
        self.btn_delete.setChecked(False)
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout_12.addWidget(self.btn_delete)
        self.btn_label = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_label.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_label.setAutoFillBackground(False)
        self.btn_label.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"")
        self.btn_label.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_label.setIcon(icon12)
        self.btn_label.setIconSize(QtCore.QSize(24, 24))
        self.btn_label.setCheckable(False)
        self.btn_label.setChecked(False)
        self.btn_label.setObjectName("btn_label")
        self.verticalLayout_12.addWidget(self.btn_label)
        self.btn_comment = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_comment.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_comment.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"")
        self.btn_comment.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/comment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_comment.setIcon(icon13)
        self.btn_comment.setIconSize(QtCore.QSize(24, 24))
        self.btn_comment.setCheckable(False)
        self.btn_comment.setChecked(False)
        self.btn_comment.setObjectName("btn_comment")
        self.verticalLayout_12.addWidget(self.btn_comment)
        self.btn_color = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_color.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_color.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"\n"
"")
        self.btn_color.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("img/paint-board-and-brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_color.setIcon(icon14)
        self.btn_color.setIconSize(QtCore.QSize(24, 24))
        self.btn_color.setCheckable(False)
        self.btn_color.setChecked(False)
        self.btn_color.setObjectName("btn_color")
        self.verticalLayout_12.addWidget(self.btn_color)
        spacerItem = QtWidgets.QSpacerItem(20, 100000000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem)
        self.btn_zoom_in = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_zoom_in.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_zoom_in.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(224, 224, 224, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"\n"
"")
        self.btn_zoom_in.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("img/add-searching.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_in.setIcon(icon15)
        self.btn_zoom_in.setIconSize(QtCore.QSize(24, 24))
        self.btn_zoom_in.setCheckable(False)
        self.btn_zoom_in.setChecked(False)
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.verticalLayout_12.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtWidgets.QPushButton(self.frame_top_tools)
        self.btn_zoom_out.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_zoom_out.setStyleSheet("QPushButton{\n"
"    background-color: rgb(42, 41, 44);\n"
"    border-style: outset;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"\n"
"")
        self.btn_zoom_out.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("img/delete-searching.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_out.setIcon(icon16)
        self.btn_zoom_out.setIconSize(QtCore.QSize(24, 24))
        self.btn_zoom_out.setCheckable(False)
        self.btn_zoom_out.setChecked(False)
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.verticalLayout_12.addWidget(self.btn_zoom_out)
        self.horizontalLayout_6.addWidget(self.frame_top_tools, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_tools)
        self.verticalLayout.addWidget(self.frame_content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stacked_workspaces.setCurrentIndex(2)
        self.stacked_tools.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Circuit Board Designer"))
        self.label_file_location.setText(_translate("MainWindow", "C:Users\\user\\Desktop\\Circuits\\test.circuit"))
        self.label_design.setText(_translate("MainWindow", "Circuit Designer"))
        self.label_convert.setText(_translate("MainWindow", "Circuit/PCB Converter"))
        self.label_file.setText(_translate("MainWindow", "File Management"))
        self.label_page_design.setText(_translate("MainWindow", "DESIGN PAGE"))
        self.label_page_convert.setText(_translate("MainWindow", "CONVERT PAGE"))
        self.label_4.setText(_translate("MainWindow", "FILE PAGE"))
        self.label.setText(_translate("MainWindow", "Create New"))
        self.label_3.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "Save As"))
        self.label_2.setText(_translate("MainWindow", "Open"))
        self.page_components.setAccessibleName(_translate("MainWindow", "page_components"))
        self.btn_resistor.setText(_translate("MainWindow", "resist"))
        self.btn_capacitor.setText(_translate("MainWindow", "capac"))
        self.btn_diode.setText(_translate("MainWindow", "diode"))
        self.btn_led.setText(_translate("MainWindow", "led"))
        self.btn_inductor.setText(_translate("MainWindow", "induct"))
        self.btn_npn_transistor.setText(_translate("MainWindow", "npn"))
        self.btn_pnp_transistor.setText(_translate("MainWindow", "pnp"))
        self.btn_switch.setText(_translate("MainWindow", "switch"))
        self.btn_ground.setText(_translate("MainWindow", "gnd"))
        self.btn_voltage.setText(_translate("MainWindow", "volt"))
        self.page_colors.setAccessibleName(_translate("MainWindow", "page_colors"))
        self.btn_black.setText(_translate("MainWindow", "black"))
        self.btn_red.setText(_translate("MainWindow", "red"))
        self.btn_orange.setText(_translate("MainWindow", "oran"))
        self.btn_yellow.setText(_translate("MainWindow", "yell"))
        self.btn_green.setText(_translate("MainWindow", "green"))
        self.btn_blue.setText(_translate("MainWindow", "blue"))
        self.btn_purple.setText(_translate("MainWindow", "purp"))
        self.btn_pink.setText(_translate("MainWindow", "pink"))
        self.btn_cyan.setText(_translate("MainWindow", "cyan"))
        self.btn_brown.setText(_translate("MainWindow", "brown"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

